[CODE] Refactoring base.py sort model to be cleaner and easier to read.
LCA-ActivityBrowser/activity-browser pull request #1297
Opened 2024-06-03 21:04 UTC by ughstudios

- Some of the code in base.py is very bad and will probably need to be changed again. However, I added type hints and removed some bad code and cleaned up a bit of the logic.

#1278 

I wrote a comment on this last pull request. 

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation, please follow the [numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] Update tests.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `feature`, `ui`, `change`, `documentation`, `breaking`, `ci`
      as they show up in the changelog.
- [ ] Link this PR to related issues by using [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
- [x] Add a milestone to the PR (and related issues, if any) for the intended release.
- [x] Request a review from another developer.

2024-06-04 07:27 UTC, cmutel commented
This is a good first step but the logic here is still broken (not your fault). The earlier call replaces only `NaN` with an empty string. Assuming that missing values are zero is maybe OK, but WRT sorting I would put missing values (i.e. ones which don't have an explicit zero) below everything, including below negative numbers.

The basic problem is that earlier in the code there is an explicit inclusion of string types into a numeric array. Once this happens there is not reliable sorting. Or, in other words, this whole function should not need to exist.

2024-06-04 08:39 UTC, marc-vdm commented
> The basic problem is that earlier in the code there is an explicit inclusion of string types into a numeric array.

Agree, plan is to update how results are processed after 2.10 sometime anyway, so this was not a priority. 

There's a related issue here: #887

2024-06-04 09:29 UTC, marc-vdm requested changes
Thanks for the PR! See separate comments for requested changes. If you have questions/comments, let me know.

In addition to requested code-changes, please update the name of your PR to something more easily understandable so we can understand/retrace from merge history/git blame what's happened and why, see the [pull-requests section of CONTRIBUTING.MD](https://github.com/LCA-ActivityBrowser/activity-browser/blob/main/CONTRIBUTING.md#pull-requests) for some pointers.

Finally, please don't remove the PR checklist when opening PRs, the checklist makes it easier for us to make sure the administrative side is roughly in order.

Thanks!

2024-06-04 09:29 UTC, marc-vdm commented on activity_browser/ui/tables/models/base.py
> -        right_data = self.sourceModel().data(right, 'sorting')
If you don't keep the `sorting` argument, the sort is done based on what is in the view, not the actual data (which is the reason `QSortFilterProxyModel` was subclassed in the first place). 

e.g. timestamps in a human readable format are not properly sorted if this argument is removed (#1151)


please restore.

2024-06-04 09:29 UTC, marc-vdm commented on activity_browser/ui/tables/models/base.py
> +        if not left_data and not right_data:
Please make all follow-up checks `elif`, that makes it clearer this is one test case, not multiple in a row.

2024-06-04 09:29 UTC, marc-vdm commented on activity_browser/ui/tables/models/base.py
>          raise ValueError(f"Cannot compare {left_data} and {right_data}, incompatible types.")
I found a missing test case that wasn't in the original code, thanks!

Please also add testing between `str` and `None` in addition to numeric and `None`. Example in UI: 2 exchanges in an activity, one with a comment and one without.

2024-06-04 16:56 UTC, marc-vdm commented on activity_browser/ui/tables/models/base.py
> -        right_data = self.sourceModel().data(right, 'sorting')
> It's not normally good practice to be passing strings like this

Ok, what _is_ good practice in this case? Happy to hear suggestions.

2024-06-04 16:57 UTC, marc-vdm commented
>I'll also look into seeing where we could make a "real" fix to the issue.

I'd suggest keeping this low on your priorities, we have on the planning to make major changes to results.

2024-06-05 07:26 UTC, marc-vdm commented on activity_browser/ui/tables/models/base.py
> -        right_data = self.sourceModel().data(right, 'sorting')
The `'sorting'` string is passed as `role` argument, Qt just doesn't provide a role for what we are doing, so we created a custom one like this. I could have written a custom role, but just passing a string is less of a mess IMO

2024-06-19 10:45 UTC, marc-vdm commented
@ughstudios We are looking to make a `2.10` release soon-ish. Will you finish the remaining task or should we close this?

2024-06-20 09:39 UTC, merged